### PR TITLE
Vlad TEE + PQC

### PR DESCRIPTION
**Pull request by Cosmodude**
# What does this PR do?
Added material about TEE (3 min read), enlarged the PQC section (1 min -> 6 min)

## Before reviewing
[ done] Check for missing / redundant content
[ done] Grammar Check
[ done] Check if the content is accurate

## Who can review?
@yijun-lee @HyesuKim-dot @abell1689neo @hwamzzx @healthykim

### CODE REVIEW

**Comment by Cosmodude** [comment]
A lot of materials about PQC. 

Should I create a separate folder and cover some points in detail?

ex. Shor's Algorithm, Grover's Algorithm, Lattice-Based Cryptography

**Comment by yijun-lee** [comment]
> A lot of materials about PQC.
> 
> Should I create a separate folder and cover some points in detail?
> 
> ex. Shor's Algorithm, Grover's Algorithm, Lattice-Based Cryptography

I think it would be better to work under Basic Cryptography! While PQC is indeed an important topic, given the nature of this project, which focuses on cryptography for blockchain, it might be better not to separate it. 
Additionally, since we can link related concepts directly in the PQC document, I don’t think there’s a need to create a separate folder. 
Feel free to share your thoughts! 😀

**Comment by Cosmodude** [comment]
Yeah, I mean creating a PQC folder under the basic cryptography folder. 

Worried that creating more files will make the Basic Cryptography folder messy.

**Comment by yijun-lee** [comment]
> Yeah, I mean creating a PQC folder under the basic cryptography folder.
> 
> Worried that creating more files will make the Basic Cryptography folder messy.

Alright, let’s go with your suggestion for now! If I feel it’s unnecessary later, I’ll make adjustments.

**Comment by hunjyeong** [comment]
I think the PET > TEE part is well written.
I think it would be good to add more content about working on blockchain projects after looking at the contents of the link.
[https://collective.flashbots.net/t/blockchain-projects-working-with-trusted-execution-environments/3539](https://github.com/decipherhub/Cryptography/pull/url)

**Comment by hunjyeong** [comment]
Post-Quantum Cryptography
1. Given this project’s interactive features, adding links to referenced concepts (e.g., RSA, ECC, …) could be helpful for users who wish to dive deeper into these topics.(Recommended by @yijun-lee )
2. In the "Categories of Post-Quantum Algorithms" section, it would be a good idea to include all examples.
3. I think it would also be good to mention the draft standards related to the content. (Example: FIPS 203 (CRYSTALS-Kyber), FIPS 204 (CRYSTALS-Dilithium), FIPS 205 (SPHINCS+))
[https://csrc.nist.gov/news/2023/three-draft-fips-for-post-quantum-cryptography](https://csrc.nist.gov/news/2023/three-draft-fips-for-post-quantum-cryptography)

**Comment by Cosmodude** [comment]
1. added interactive links, please check if missed sth
2. didn't get the point, please mention more examples if I missed sth 
3. added links to NIST

**Comment by Cosmodude** [comment]
I would like to continue by writing about 
1. Grover's and Shor's Algorithms
2. Categories of Post-Quantum Algorithms
3. four algorithms chosen for standardization

**Review by yijun-lee — APPROVED** [review]
LGTM! 
Let’s proceed with additional tasks in a separate PR.

**Pull request merged**
